### ISSUE TITLE
Paywall not showing up when no options set

### ISSUE THREAD

**Issue by cryptoteun** [getAlby/lightning-publisher-wordpress#15]
When I add only `[lnpaywall]` this is showing up as text on the post:
![image](https://user-images.githubusercontent.com/73664763/189738191-9100bbe9-bd7e-4a4a-8afb-8e04a0b8efe3.png)

When I add for example the currency like: `[lnpaywall currency="EUR"]` it is working fine.

Additional: I'm using Classic Editor as editor instead of Gutenberg.

**Comment by bumi** [comment]
thanks for reporting this! 
https://github.com/getAlby/lightning-publisher-wordpress/commit/cb0a3c7560e6aa7be4bc6aea2f5d39a90f62c841
