### ISSUE TITLE
"Undefined" for Paywall and Donation not working at all

### ISSUE THREAD

**Issue by velaia** [getAlby/lightning-publisher-wordpress#20]
I've been running the v1.2.0 and the latest version (ZIP download) from now. I added an getalby.com address and got the "connected" message at the Wallet setting (also a BTCPay sever before).

When I add the Lightning Paywall and click "Pay", I only get some text "undefined".

The donation button just switches right to the "Donation successful" confirmation message without displaying any donation dialogue.

Where can I find more debugging information? I'm on WordPress 6.0.2.

**Comment by bumi** [comment]
thanks for reporting this. 
This must be likely because the lightning invoice could not be created. Can you open the LNURL it gives you in the "connected" message (e.g. https://getalby.com/.well-known/lnurlp/michael)

Can I see your installation somewhere? Which Alby LN address do you use (feel free to email me)

**Comment by bumi** [comment]
@velaia also I have just made a patch release: https://github.com/getAlby/lightning-publisher-wordpress/releases/tag/v.1.2.1
this should no longer silently fail when the lightning invoice could not be created.

**Comment by velaia** [comment]
The version with my getalby.com address works.

The one with my own BTCPay server still fails. I'll send you details in a private message.

**Comment by velaia** [comment]
@bumi helped me through this privately and we found out that the in BTCPay Server you need more permissions than the first two. With the following permissions it seems to be working fine for me:

<img width="391" alt="image" src="https://user-images.githubusercontent.com/1515904/196053989-8163c1ee-86c0-41c3-a41e-0738e0d5d792.png">
