### ISSUE TITLE
Transactions with the Twentyuno Lightning Payment Widget don´t appear in the transactions lists

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-publisher-wordpress#21]
I could not find the transaction in the list, when I used the Twentyuno Lightning Payment Widget on https://wp.play.getalby.com

**Comment by bumi** [comment]
yep, I think this is a won't fix because of technical reasons (that I don't know right now anymore) I think the "normal" LNURL payments (which is used by the widget) are not stored.
