### ISSUE TITLE
Review and update for 6.2

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-publisher-wordpress#28]
WordPress 6.2 is scheduled for release on March 28th, 2023. Are your plugins ready?

**Comment by Bobz-zg** [comment]
@bumi  Looks like we are all good here.

What needs to be done when updates like this come is check [release notes](https://wordpress.org/documentation/wordpress-version/version-6-2/)

There is a [Field Guide](https://make.wordpress.org/core/2023/03/09/wordpress-6-2-field-guide/) article included with each release with developer notes.

Obviously a test needs to be done as well.
It would maybe be helpful to write down which scenarios need to be tested before we say we are good to go.
Ideally, in the future this can be automated.
