### ISSUE TITLE
Not working with latest version of Wordpress 6.5.4

### ISSUE THREAD

**Issue by joemoraca** [getAlby/lightning-publisher-wordpress#45]
I get this error when I use my getalby.com LNaddress I can setup a post and see the button but clicking on it gives error

`Connection Error GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: gatalby.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://gatalby.com/.well-known/lnurlp/nomadjoe in /var/www/html/wp-content/plugins/bitcoin-lightning-publisher/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210 Stack trace: #0 /var/www/html/wp-content/plugins/bitcoin-lightning-publisher/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection() #1 /var/www/html/wp-content/plugins/bitcoin-lightning-publisher/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError() #2 /var/www/html/wp-content/plugins/bitcoin-lightning-publisher/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish() #3 /var/www/html/wp-content/plugins/bitcoin-lightning-publisher/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke() #4 /var/www/html/wp-content/plugins/bitcoin-lightning-publisher/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}() #5 /var/www/html/wp-content/plugins/bitcoin-lightning-publisher/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}() #6 /var/www/html/wp-content/plugins/bitcoin-lightning-publisher/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke() #7 /var/www/html/wp-content/plugins/bitcoin-lightning-publisher/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}() #8 /var/www/html/wp-content/plugins/bitcoin-lightning-publisher/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke() #9 /var/www/html/wp-content/plugins/bitcoin-lightning-publisher/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}() #10 /var/www/html/wp-content/plugins/bitcoin-lightning-publisher/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke() #11 /var/www/html/wp-content/plugins/bitcoin-lightning-publisher/vendor/guzzlehttp/guzzle/src/Client.php(107): GuzzleHttp\Client->transfer() #12 /var/www/html/wp-content/plugins/bitcoin-lightning-publisher/vendor/guzzlehttp/guzzle/src/Client.php(123): GuzzleHttp\Client->sendAsync() #13 /var/www/html/wp-content/plugins/bitcoin-lightning-publisher/includes/clients/lightning-address.php(121): GuzzleHttp\Client->send() #14 /var/www/html/wp-content/plugins/bitcoin-lightning-publisher/includes/clients/lightning-address.php(28): LightningAddress->request() #15 /var/www/html/wp-content/plugins/bitcoin-lightning-publisher/includes/clients/abstract-class-bln-publisher-client.php(91): LightningAddress->getInfo() #16 /var/www/html/wp-content/plugins/bitcoin-lightning-publisher/admin/settings/class-dashboard.php(57): Abstract_BLN_Publisher_Client->getInfo() #17 /var/www/html/wp-content/plugins/bitcoin-lightning-publisher/admin/templates/settings/page-dashboard.php(28): LNP_Dashboard->get_connected_wallet() #18 /var/www/html/wp-content/plugins/bitcoin-lightning-publisher/admin/settings/class-abstract-settings.php(116): include('...') #19 /var/www/html/wp-includes/class-wp-hook.php(324): LNP_SettingsPage->renderer() #20 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #21 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action() #22 /var/www/html/wp-admin/admin.php(259): do_action() #23 {main}`

**Comment by bumi** [comment]
I think you have a typo in your lightning address `gatalby` instead of `gEtalby.com`

but we're also preparing a new release.

**Comment by joemoraca** [comment]
Sorry to have wasted your time. ;-(   If I can help in any way for your next release please let me know.
